### ISSUE TITLE
[2019-08-23 04:51:32,830] root.ERROR MainThread Failed to parse key from __consumer_offsets topic message. Key: b'\x00\x00\x00\x01'

### ISSUE THREAD

**Issue by akunszt** [braedon/prometheus-kafka-consumer-group-exporter#34]
We got zillions (nearly 20GiB under two hours) messages like this.

```
2019-08-23T04:51:36.136+00:00 10.1.220.207 d09224a59d00[3458]: [2019-08-23 04:51:32,830] root.ERROR MainThread Failed to parse key from __consumer_offsets topic message. Key: b'\x00\x00\x00\x01'
2019-08-23T04:51:36.136+00:00 10.1.220.207 d09224a59d00[3458]: Traceback (most recent call last):
2019-08-23T04:51:36.136+00:00 10.1.220.207 d09224a59d00[3458]:   File "/usr/src/app/prometheus_kafka_consumer_group_exporter/parsing.py", line 38, in parse_key
2019-08-23T04:51:36.137+00:00 10.1.220.207 d09224a59d00[3458]:     key_dict['topic'], remaining_key = read_string(remaining_key)
2019-08-23T04:51:36.137+00:00 10.1.220.207 d09224a59d00[3458]:   File "/usr/src/app/prometheus_kafka_consumer_group_exporter/parsing.py", line 24, in read_string
2019-08-23T04:51:36.137+00:00 10.1.220.207 d09224a59d00[3458]:     length, remaining = read_short(bytes)
2019-08-23T04:51:36.137+00:00 10.1.220.207 d09224a59d00[3458]:   File "/usr/src/app/prometheus_kafka_consumer_group_exporter/parsing.py", line 6, in read_short
2019-08-23T04:51:36.137+00:00 10.1.220.207 d09224a59d00[3458]:     num = unpack_from('>h', bytes)[0]
```

It resembles to a previous [issue](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/issues/22). The code doesn't terminate anymore but the amount of logs kills our infrastructure. As those messages can't be parsed at all we implemented a temporary fix to drop those messages early, not even try to parse them.

```patch
diff --git a/prometheus_kafka_consumer_group_exporter/parsing.py b/prometheus_kafka_consumer_group_exporter/parsing.py
index c565381..d602f04 100644
--- a/prometheus_kafka_consumer_group_exporter/parsing.py
+++ b/prometheus_kafka_consumer_group_exporter/parsing.py
@@ -28,6 +28,10 @@ def read_string(bytes):
 
 
 def parse_key(bytes):
+    # we can't parse this messages anyway, drop them quickly to avoid zillions of tracebacks
+    if bytes == b'\x00\x00\x00\x01' or bytes == b'\x00\x00\x00\x00':
+        return None
+
     try:
         (version, remaining_key) = read_short(bytes)
         key_dict = {'version': version}
```

I didn't created a PR as I'm not sure if this is helpful to others and if it's the correct way to handle them.

**Comment by braedon** [comment]
Hi @akunszt, that's not a very ideal situation - sorry about that!

I'm curious as to where these bad messages are coming from - I've never run into them myself. Have you recently upgraded Kafka - what version are you running? Are you running a managed Kafka version (e.g. Amazon MSK), or a streaming platform on top of Kafka like Spark? Are you running anything else that could be writing to `__consumer_offsets`? Alternatively, if you could find one of these messages in your `__consumer_offsets` topic and send me the message value, it'd be great.

Regardless, @jutley has proposed changing the logging level of these messages to `WARNING` over in https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/31. That would allow you to disable this logging by setting `--log-level=ERROR`. Would that work for your situation?

**Comment by akunszt** [comment]
Hi @braedon!

Thanks for the response! Actually @jutley and I are working together and he is the Kafka expert in the team. So he can explain to you where this messages comes from. I'm responsible for the logging infra so I approached the problem from that direction (aka I don't know what are you but you have the right to remain silent!).

We're not using any managed Kafka version, we're running the `wurstmeister/kafka:2.12-2.2.1` Docker image and we update it on a regular basis.

If [#31](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/31) is merged than it'll solve this issue as well as we're already using `--log-level=ERROR`. In that case it won't worth to merge my changes at all.

**Comment by braedon** [comment]
I see - that explains the "coincidental" issue/pr alignment then :smile: 

@jutley If you can get me any more info on what the problematic messages are/where they come from, it'd be great. We can proceed on with https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/31 in the meantime, however.

**Comment by jutley** [comment]
Okay, I've been digging on this, and I think I have a pretty good understanding at what's happening.

Only one of our Kafka clusters causes this exporter to print these error messages. After looking at the details of these messages, I've noticed that they are all control messages for transactions. This cluster is the only one that has any transactional offset commits.

Additionally, I found this issue which reports that this kafka consumer does not handle transactional messages, and gives incorrect keys and values, which lines up nicely with what we're observing.
https://github.com/dpkp/kafka-python/issues/1853

One solution would be to simple skip any messages that are a control message, but unfortunately the client does not expose this information to the end client. I've verified the Confluent's python client also does not support transactional messages at this time.
https://github.com/confluentinc/confluent-kafka-python/issues/357

I've also verified that the fact that the library is return control messages to the end client is a bug. [This protocol guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) explicitly states:
> Clients should not return control batches (ie. those with this bit set) to applications. (since 0.11.0.0)

In our case, all these messages have the exact same key (and slightly different values). I'm wondering whether this is true for just us, or whether it's universally true. If the latter, we can implement a hacky workaround to watch for any messages with this key and skip them.

**Comment by jutley** [comment]
Based on all the issues the kafka-python library is producing for us, I'm starting to believe that this type of exporter needs to be written in a JVM language in order to use the official Java library. This is unfortunate given that we've used these metrics in so many dashboards and alerts, but it's looking increasingly necessary. 

This exporter seems like a viable option:
https://github.com/lightbend/kafka-lag-exporter

**Comment by braedon** [comment]
Thanks for digging into this. It's rather unfortunate that Kafka effectively broke client backwards compatibility in 0.11.0 ☹️.

My guess is the log level change in https://github.com/braedon/prometheus-kafka-consumer-group-exporter/pull/31 is the best workaround for now. Lets get that in, even if you decide to switch exporters.

**Comment by braedon** [comment]
With version [0.5.3](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.3), setting `--log-level=ERROR` will hide these error messages.

I'll leave this issue open for now, in case https://github.com/dpkp/kafka-python/issues/1853 gets resolved.

**Comment by WesleyBatista** [comment]
> I've noticed that they are all control messages for transactions

Thank you @jutley  for the time spent and the clarification! 

We experienced similar issue here (not related to this package though).

On our case the error was when parsing the value of the kafka message.

We found out that replacing the _kafka-python_ library with **aiokafka** might be a solution. tested here and apparently the library "ignore" the messages:

```
offset=4980 key=b'c4fbfcd0-8ad3-43e2-995d-1f042286063a' value={...}
offset=4982 key=b'bf6dddac-443e-45ad-ad57-c12a754ae4ad' value={...}
offset=4984 key=b'8cfe0799-7a5b-47b0-a738-ab58003ce0cb' value={...}
```

**Comment by nilansaha** [comment]
Any update on this guys ?

**Comment by jutley** [comment]
@nilansaha Been a while since I looked at this, but I believe we just set the log level to skip these messages. Sorry I can't be more helpful!

**Comment by nilansaha** [comment]
> @nilansaha Been a while since I looked at this, but I believe we just set the log level to skip these messages. Sorry I can't be more helpful!

Hi @jutley that's alright. Do you happen to know if confluent kafka python library can ignore these control messages ? I am having a really hard time replicating these control messages locally hence the question. Not sure if you have some handy code lying around to generate those.

**Comment by jutley** [comment]
@nilansaha 

> Do you happen to know if confluent kafka python library can ignore these control messages ?

I took a look at the docs, and they seem to indicate that the library does support transactional messages.
https://github.com/confluentinc/confluent-kafka-python/blob/d9a91a3d74c6447d53ba1c5733b0f99c2db2e259/docs/index.rst#transactional-producer-api

> Not sure if you have some handy code lying around to generate those.

You should be able to use the console-producer to do this. Just set the transaction configuration as necessary. If you are able to access the broker's log data, you should be able to run the "dump log segments" tool to verify the transaction markers are on the topic data.
https://www.oreilly.com/library/view/apache-kafka-cookbook/9781785882449/ch04s03.html

I think that is the extent of the help I can provide at this point. Hope that helps!
